/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codehunter.hibernate_pure_playground;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {
    private static final Logger log = LogManager.getLogger(App.class);
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        log.info("App is running");
        System.out.println(new App().getGreeting());
   is
}
